# See https://cloud.google.com/appengine/docs/standard/go/config/appref
version: 1
runtime: go
api_version: go1.9
service: dev-bot

handlers:
- url: /.*
  script: _go_app

nobuild_files:
- vendor/
- .git/

skip_files:
- vendor/
- .git/
